version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zero3d_prod_db
    restart: unless-stopped
    env_file:
      - ./Client-Back-Zero3D/.env.production 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Client-Back-Zero3D/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zero3d_prod_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d zero3d_prod_db"]
      interval: 10s
      retries: 5

  frontend:
    build: 
      context: ./Client-Front-Zero3D
      dockerfile: Dockerfile
    image: zero3d-frontend:prod
    container_name: zero3d_prod_front 
    environment:
      - NODE_ENV=production
    networks:
      - zero3d_prod_network


  backend:
    build:
      context: ./Client-Back-Zero3D
      dockerfile: Dockerfile.prod
    container_name: zero3d_prod_back
    image: zero3d-backend:prod
    env_file:
      - ./.env.production 
    environment:
      - DJANGO_SETTINGS_MODULE=appBackClient.settings.production
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - zero3d_prod_network
    

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: zero3d_prod_nginx
    image: zero3d-nginx:prod
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./Client-Front-Zero3D/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - zero3d_prod_network
      
  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: zero3d_prod_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - zero3d_prod_network

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:

networks:
  zero3d_prod_network:
    driver: bridge