version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zero3d_stage_db
    restart: unless-stopped
    env_file:
      - ./Client-Back-Zero3D/.env.staging
    environment:
      POSTGRES_DB: zero3d_stage_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
      - ./Client-Back-Zero3D/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zero3d_stage_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d zero3d_stage_db"]
      interval: 10s
      retries: 5


  backend:
    build:
      context: ./Client-Back-Zero3D
      dockerfile: Dockerfile
    container_name: zero3d_django_back
    image: zero3d-backend:stage
    env_file:
      - ./Client-Back-Zero3D/.env.staging 
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - static_volume_stage:/app/staticfiles
    networks:
      - zero3d_stage_network

  frontend:
    build: 
      context: ./Client-Front-Zero3D
      dockerfile: Dockerfile
    image: zero3d-frontend:stage
    container_name: zero3d_preact_front 
    environment:
      - NODE_ENV=production
    volumes:
    - frontend_dist_stage:/dist
    networks:
      - zero3d_stage_network

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: zero3d_stage_nginx
    image: zero3d-nginx:stage
    cpuset: "0"
    cpus: "1.0"
    ports:
      - "8080:80"
    volumes:
      - static_volume_stage:/app/staticfiles
      - frontend_dist_stage:/usr/share/nginx/html:ro
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - zero3d_stage_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: zero3d_stage_pgAdmin
    env_file:
      - ./Client-Back-Zero3D/.env.staging
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data_stage:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - zero3d_stage_network


  portainer:
    image: portainer/portainer-ce:latest
    container_name: zero3d_stage_portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_stage:/data
    ports:
      - "9001:9000"
    networks:
      - zero3d_stage_network

volumes:
  postgres_data_stage:
  pgadmin_data_stage:
  static_volume_stage:
  frontend_dist_stage:
  portainer_data_stage:

networks:
  zero3d_stage_network:
    driver: bridge