version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zero3d_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: zero3d_dev_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./Client-Back-Zero3D/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - zero3d_dev_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d zero3d_dev_db"]
      interval: 10s
      retries: 5


  backend:
    build:
      context: ./Client-Back-Zero3D
      dockerfile: Dockerfile
    container_name: zero3d_dev_back
    command: /app/entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: appBackClient.settings.development
      DB_NAME: zero3d_dev_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
      SLIC3R_PATH: /usr/bin/slic3r
      ALLOWED_HOSTS: localhost,127.0.0.1
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - ./Client-Back-Zero3D:/app
    ports:
      - "8000:8000"
    networks:
      - zero3d_dev_network


  frontend:
    build:
      context: ./Client-Front-Zero3D
      dockerfile: Dockerfile
    container_name: zero3d_dev_front 
    command: npm run dev
    volumes:
      - ./Client-Front-Zero3D:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - zero3d_dev_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: zero3d_dev_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  
    depends_on:
      - db
    networks:
      - zero3d_dev_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: zero3d_dev_portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - zero3d_dev_network

volumes:
  postgres_data_dev:
  pgadmin_data:
  portainer_data:  ##

networks:
  zero3d_dev_network:
    driver: bridge