version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - ./Client-Back-Zero3D/.env.production
    environment:
      POSTGRES_DB: zero3d_prod_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - zero3d_prod_postgres_data:/var/lib/postgresql/data
      - ./Client-Back-Zero3D/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zero3d_prod_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d zero3d_prod_db"]
      interval: 10s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  backend:
    image: juliancabanillas/zero3d-backend:prod-v0.05
    env_file:
      - ./Client-Back-Zero3D/.env.production
    depends_on:
      - db
    networks:
      - zero3d_prod_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure



  nginx:
    image: juliancabanillas/zero3d-frontend:prod-v0.057
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - zero3d_prod_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./Client-Back-Zero3D/.env.production
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - zero3d_prod_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - zero3d_prod_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - zero3d_prod_portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - zero3d_prod_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  zero3d_prod_postgres_data:
  zero3d_prod_pgadmin_data:
  zero3d_prod_static_volume:
  zero3d_prod_frontend_dist:
  zero3d_prod_portainer_data:

networks:
  zero3d_prod_network:
    driver: overlay
