version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zero3d_stage_db
    restart: unless-stopped
    env_file:
      - ./Client-Back-Zero3D/.env.staging
    environment:
      POSTGRES_DB: zero3d_stage_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
      - ./Client-Back-Zero3D/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zero3d_stage_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d zero3d_stage_db"]
      interval: 10s
      retries: 5


  backend:
    build:
      context: ./Client-Back-Zero3D
      dockerfile: Dockerfile
    container_name: zero3d_django_back
    image: zero3d-backend:prod
    env_file:
      - ./Client-Back-Zero3D/.env.staging 
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - static_volume_stage:/app/staticfiles
    networks:
      - zero3d_stage_network

  frontend:
    build: 
      context: ./Client-Front-Zero3D
      dockerfile: Dockerfile
    image: zero3d-frontend:prod
    container_name: zero3d_preact_front 
    environment:
      - NODE_ENV=production
    volumes:
    - frontend_dist:/dist
    networks:
      - zero3d_stage_network

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: zero3d_nginx_rp
    image: zero3d-nginx:prod
    ports:
      - "80:80"
    volumes:
      - static_volume_stage:/app/staticfiles
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - zero3d_stage_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: zero3d_pgAdmin
    env_file:
      - ./Client-Back-Zero3D/.env.staging
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - zero3d_stage_network

volumes:
  postgres_data_stage:
  pgadmin_data:
  static_volume_stage:
  frontend_dist:

networks:
  zero3d_stage_network:
    driver: bridge